global using congestion_tax_calculator_contractor.Enums;
global using congestion_tax_calculator_contractor.Requests;
global using congestion_tax_handler.Interfaces;
global using congestion_tax_handler.Models;
global using congestion_tax_handler.Vehicles;